RGBLIGHT_ENABLE = no

CAPS_WORD_ENABLE = yes


SRC += erikpeyronson.c

# Optional features
CONSOLE_ENABLE = yes

RGB_MATRIX_ENABLE = yes
OLED_ENABLE = yes
TAP_DANCE_ENABLE = yes
ENCODER_ENABLE = yes
REPEAT_KEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RAW_ENABLE = yes
